/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":api"))
    implementation(project(":server-base"))
    implementation(libs.dropwizard.core)
    implementation(libs.commons.codec)

    implementation(libs.bundles.logging)

    implementation(libs.javax.inject)
    implementation(libs.dagger)
    annotationProcessor(libs.dagger.compiler)
    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)

    implementation(libs.micrometer.core)
    implementation(libs.codehead.metrics)
    implementation(libs.codehead.metrics.micrometer)

    testImplementation(libs.dropwizard.testing)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
    testImplementation(libs.codehead.metrics.test)
    testAnnotationProcessor(libs.dagger.compiler)
    testAnnotationProcessor(libs.immutables.value)
}

application {
    mainClass.set("com.codeheadsystems.keys.KeysServer")
}
