/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(libs.jackson.databind)
    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)

    // IOC
    implementation(libs.javax.inject)

    // Database
    implementation(libs.liquibase.core)
    implementation(libs.bundles.jdbi)
    testImplementation(libs.bundles.jdbi.testing)
    testImplementation(libs.hsqldb)

    testAnnotationProcessor(libs.immutables.value)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
}

