/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(libs.dropwizard.core) // TODO: use where the paths really come from, not core.

    implementation(libs.javax.inject)
    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)

    testImplementation(libs.bundles.logback)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
    testAnnotationProcessor(libs.immutables.value)
}

